apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
      app: my-app
spec:
  containers:
  - name: my-app-container
    image: myapp:monitoring
    imagePullPolicy: Never
    ports:
    - containerPort: 4000  # שנה לפי הפורט שהאפליקציה שלך מאזינה עליו
