apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 4000          # פורט פנימי בתוך הקלאסטר
      targetPort: 4000    # פורט שבו האפליקציה באמת מאזינה בתוך הפוד
      nodePort: 30007     # פורט קבוע בגישה מבחוץ (בין 30000 ל-32767)
